name: onestar_mapping

channels:
    - conda-forge

dependencies:
    - python=3.10
    - numpy
    - pandas
    - conda-forge::jupyterlab
    - conda-forge::matplotlib
    - conda-forge::seaborn
    - conda-forge::geopy
    - conda-forge::geopandas
    - conda-forge::shapely
    - openpyxl
    - conda-forge::python-wget
